version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - louis-vs
    assignees:
      - louis-vs
  - package-ecosystem: yarn
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - louis-vs
    assignees:
      - louis-vs
